### ISSUE TITLE
Missing brackets on name

### ISSUE THREAD

**Issue by marcosmarp** [KostaSav/hp-api#39]
Hi! In `characters.json` line **1109** there is a pair of missing brackets.

It currenly looks like this:
 `"alternate_names": "Dame Phyllida Spore",`

And it should look like this:
`"alternate_names": ["Dame Phyllida Spore"],`

Thanks and I love the API!

**Comment by KostaSav** [comment]
Thanks @marcosmarp for spotting this!

**Comment by marcosmarp** [comment]
@KostaSav wanted to let you know that the API still sends the name without the brackets, maybe it needs to be reseted?

**Comment by KostaSav** [comment]
No, it is just that I made the change on one branch (master),
Once @bethfraser merges it to the one linked to the API (heroku branch), we'll be able to see it there.
