### ISSUE TITLE
Billy Stubbs flagged as Hogwarts Student

### ISSUE THREAD

**Issue by marcosmarp** [KostaSav/hp-api#41]
Hey! It's me again. In line **8337** in the data, Billy Stubbs is flagged as a Hogwarts student; unless I'm missing something, he was just a muggle boy barely mentioned as a Voldemort's related orphan.

Thanks!

**Comment by KostaSav** [comment]
Hi!
Indeed, this value was missed for both Billy Stubbs and Amy Benson during copy-pasting.

Thanks again and keep it up!
