### ISSUE TITLE
some characters have no image

### ISSUE THREAD

**Issue by francoders** [KostaSav/hp-api#49]
some details need to be added to the api, but it has a lot of characters, thanks.

**Comment by KostaSav** [comment]
You can make a pull request with the images and details you want to add to the API (about the images, I am not sure if we are allowed to use whatever from the internet),
About the number of characters, blame the author!
(sorry but I cannot understand the point of this issue)

**Comment by francorvalant** [comment]
I'm sorry, I expressed myself badly.
It is because of the images, several are missing. But the most important thing is that there are repeated characters and they have no id which causes duplicates and gives problems with the key.
