### ISSUE TITLE
Different types for same property

### ISSUE THREAD

**Issue by devesmee** [KostaSav/hp-api#57]
Hi!
I'm currently trying to implement this api into an iOS app and I run into the problem of the same property having different types. For example, the yearOfBirth has either an Int value or a String value. The wand length can be an Int, Double or a String. Is there a specific reasoning behind why these are different types?

Thanks in advance

**Comment by KostaSav** [comment]
Hi @devesmee ,
No, there is not a specific reasoning. These are probably bugs that need to be resolved and agree on a specific datatype for each field.
You can open a pull request for any inconsistencies you find and fix. Otherwise, I will have a look as well when I have the chance.

**Comment by devesmee** [comment]
Hi @KostaSav,
Would you like both of them to be a String and then an empty String when there is no value? 
Or the yearOfBirth as an Int, the wand length as a Double and then a null value when no value is known?

**Comment by KostaSav** [comment]
I am not sure, thinking about it.
What do you thing would be the best approach @devesmee? What would be easier/most effective for your iOS app and perhaps for other apps using this API?

**Comment by devesmee** [comment]
Swift (iOS) and Kotlin (Android) can easily handle optional properties, but I am not sure about any other programming languages that people are using in combination with this API and how those languages handle optionals. It wouldn't be good if other peoples 'existing apps/websites break because of using a null-value, but personally I would prefer using null so you can keep yearOfBirth as an Int and wand length as a Double instead of using a String.

But really it is up to you, I can make it work with a String also :)

**Comment by KostaSav** [comment]
@devesmee 
I have changed to null values for missing yearOfBirth and wand length. Please check if it's OK now.

About the integer/double values for wand length, I am not sure if that also causes issues. If it does, a JSON schema needs to be created with the datatypes of each field.

**Comment by devesmee** [comment]
@KostaSav 
Works perfectly fine! Somehow Swift takes an Int value and automatically converts it to a Double, so that change is not needed. 
Thanks for your help!
