### ISSUE TITLE
Data without ID's

### ISSUE THREAD

**Issue by Falkaniere** [KostaSav/hp-api#62]
Hi! 
Im currently using this API on some iOS app and I notice that the data of all characters has no id. Can I open a PR to fix it? Or we have some reason for this?

**Comment by KostaSav** [comment]
Hi @Falkaniere ,
Yes please, it would be great if you could make a pull request to fix that.
Thanks!

**Comment by Falkaniere** [comment]
Nice! I open this PR https://github.com/KostaSav/hp-api/pull/63
