### ISSUE TITLE
No 404 handling route

### ISSUE THREAD

**Issue by LuisFloresV** [KostaSav/hp-api#82]
Just to report there's no middleware to handle the 404.

**Comment by KostaSav** [comment]
Hi @LuisFloresV ,

I have added a [commit](https://github.com/KostaSav/hp-api/commit/a3cf3cde3d295ad019f3abf4086462b318a7f82a), based on [How add middleware for 404 errors on express](https://stackoverflow.com/a/62748486/9107245).

Can you please elaborate on why we need this?

Also, feel free to create a pull request with any further changes you consider necessary. Perhaps we can create a nice 404 error page with a Harry Potter image.

Thanks!
